[workspace]
members = ["day1", "day2", "day3", "day4", "day5", "day6"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.93"
tokio = {version = "1.41.1", features = ["rt-multi-thread", "macros", "fs", "io-util"]}
thiserror = "2.0.3"
